// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Picterest.Context;

#nullable disable

namespace Picterest.Migrations
{
    [DbContext(typeof(ImageDbContext))]
    [Migration("20260805054209_addedUserEntityWithGithubSupport")]
    partial class addedUserEntityWithGithubSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Picterest.DbModels.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("bucket");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("content_type");

                    b.Property<int>("DeleteAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("delete_attempts");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("file_name");

                    b.Property<string>("LastDeleteError")
                        .HasColumnType("text")
                        .HasColumnName("last_delete_error");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("object_key");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<DateTime?>("StorageDeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("storage_deleted_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("cleanupStatus")
                        .HasColumnType("integer")
                        .HasColumnName("clean_up_status");

                    b.HasKey("Id");

                    b.HasIndex("Bucket");

                    b.HasIndex("ObjectKey")
                        .IsUnique();

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Picterest.DbModels.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("RestoredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("restored_at");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Picterest.DbModels.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<long>("GithubId")
                        .HasColumnType("bigint")
                        .HasColumnName("github_id");

                    b.Property<string>("GithubUserName")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("github_user_name");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("GithubId")
                        .IsUnique();

                    b.HasIndex("GithubUserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Picterest.DbModels.Image", b =>
                {
                    b.HasOne("Picterest.DbModels.File", "Files")
                        .WithOne("Image")
                        .HasForeignKey("Picterest.DbModels.Image", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Files");
                });

            modelBuilder.Entity("Picterest.DbModels.File", b =>
                {
                    b.Navigation("Image")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
